version: '3.8'
services:

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    volumes:
      - mariadb:/var/lib/mysql

  wordpress:
    image: erseco/alpine-wordpress
    build: .
    restart: unless-stopped
    environment:
      - WP_LANGUAGE=en_US
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_NAME=wordpress
      - DB_USER=wordpress
      - DB_PASS=wordpress
      - DB_PREFIX=wp_
      - WP_ADMIN_EMAIL=admin@example.com
      - WP_ADMIN_USERNAME=admin
      - WP_ADMIN_PASSWORD=PLEASE_CHANGEME
      - WP_DEBUG=false
      - WP_THEME=
      - WP_PLUGINS=
      - WP_SITE_TITLE="WordPress Site"
      - WP_SITE_DESCRIPTION="Just another WordPress site"
      - WP_SITE_URL=http://localhost:8080

    ports:
      - 8080:8080
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - mariadb

volumes:
  mariadb: null
  wordpress: null
