name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout
        uses: actions/checkout@v5

      # Step 2: Prepare variables for building and tagging the image
      - name: Prepare
        id: prepare
        run: |
          GHCR_IMAGE=ghcr.io/${GITHUB_REPOSITORY}
          DOCKER_PLATFORMS=linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/386,linux/ppc64le,linux/s390x

          # Determine VERSION based on GITHUB_REF
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            FULL_VERSION=${GITHUB_REF#refs/tags/} # Extract full tag name
            VERSION=$(echo $FULL_VERSION | sed 's/\//-/g') # Extract tag name and replace / with -
            WP_VERSION=$(echo $FULL_VERSION | cut -d'-' -f1) # Extract main version part for WordPress
          else
            VERSION="latest" # Use 'latest' as the default version
            WP_VERSION="latest"
          fi

          TAGS="${GITHUB_REPOSITORY}:${VERSION}"

          # Additional tag for latest on tag push
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            TAGS="$TAGS,${GITHUB_REPOSITORY}:latest"
          fi

          GHCR_TAGS="${GHCR_IMAGE}:${VERSION}"

          # Additional GHCR tag for latest on tag push
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            GHCR_TAGS="$GHCR_TAGS,${GHCR_IMAGE}:latest"
          fi

          echo "platforms=${DOCKER_PLATFORMS}" >> $GITHUB_OUTPUT
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT
          echo "ghcr-tags=${GHCR_TAGS}" >> $GITHUB_OUTPUT
          echo "wp-version=${WP_VERSION}" >> $GITHUB_OUTPUT

      # Step 3: Set up QEMU for multi-platform builds
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      # Step 4: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx

      # Step 5: Login to DockerHub
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 5.5: Login to GitHub Container Registry
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Step 6: Debug Build
      - name: Debug Build on PR
        run: |
          docker buildx build --load .

      # Step 7: Test the built image
      - name: Test
        run: |
          docker compose version
          docker compose --file docker-compose.test.yml up --exit-code-from sut --timeout 10 --build

      # Step 8: Build and Push (if not a PR)
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prepare.outputs.tags }}
          platforms: ${{ steps.prepare.outputs.platforms }}
          build-args: WORDPRESS_VERSION=${{ steps.prepare.outputs.wp-version }}

      # Step 9: Push to GitHub Container Registry
      - name: Push to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.prepare.outputs.ghcr-tags }}
          platforms: ${{ steps.prepare.outputs.platforms }}
          build-args: WORDPRESS_VERSION=${{ steps.prepare.outputs.wp-version }}

      # Step 10: Update Docker Hub Description
      - name: Docker Hub Description
        if: startsWith(github.ref, 'refs/tags/')
        uses: peter-evans/dockerhub-description@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          short-description: ${{ github.event.repository.description }}
