name: Check WordPress Version and Tag

on:
  schedule:
    - cron: '0 0 * * *' # Runs this task daily at midnight
  workflow_dispatch: # Allows manually triggering

jobs:
  check-version-and-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        tags: true 

    - name: Check WordPress Latest Version
      id: check_wp
      run: |
        LATEST_WP_VERSION=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].version')
        echo "LATEST_WP_VERSION=$LATEST_WP_VERSION" >> $GITHUB_ENV

    - name: Create Tag if New
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LATEST_WP_VERSION: ${{ env.LATEST_WP_VERSION }}
      run: |
        CURRENT_VERSION=$(git tag --sort=-v:refname | head -n 1)
        echo "Latest WP Version from API: $LATEST_WP_VERSION"
        echo "Current WP version from Git tags: $CURRENT_VERSION"
        if [ "$CURRENT_VERSION" != "$LATEST_WP_VERSION" ]; then
         echo "Creating new tag for $LATEST_WP_VERSION"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag $LATEST_WP_VERSION
          git push origin $LATEST_WP_VERSION
          echo "::set-output name=tag_created::true"
        else
          echo "Latest version is already tagged."
          echo "::set-output name=tag_created::false"
        fi
      outputs:
        tag_created: ${{ steps.tag_condition.outputs.tag_created }} # Asegura que el nombre del paso coincida


    - name: Trigger Build Workflow
      needs: check-version-and-tag
      if: ${{ needs.check-version-and-tag.outputs.tag_created == 'true' }}
      run: |
        curl -X POST \
        -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.GH_PAT }}" \
        https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
        -d '{"ref":"refs/tags/<tu_tag>"}'
      env:
        GH_PAT: ${{ secrets.GH_PAT }}