name: Check WordPress Version and Tag

on:
  schedule:
    - cron: '0 0 * * *' # Runs this task daily at midnight
  workflow_dispatch: # Allows manually triggering

jobs:
  check-version-and-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check WordPress Latest Version
      id: check_wp
      run: |
        LATEST_WP_VERSION=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].version')
        echo "LATEST_WP_VERSION=$LATEST_WP_VERSION" >> $GITHUB_ENV

    - name: Create Tag if New
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LATEST_WP_VERSION: ${{ env.LATEST_WP_VERSION }}
        GH_PATH: ${{ secrets.GH_PATH }}
      run: |
        CURRENT_VERSION=$(git tag --sort=-v:refname | head -n 1)
        echo "Latest WP Version from API: $LATEST_WP_VERSION"
        echo "Current WP version from Git tags: $CURRENT_VERSION"
        if [ "$CURRENT_VERSION" != "$LATEST_WP_VERSION" ]; then
         echo "Creating new tag for $LATEST_WP_VERSION"
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag $LATEST_WP_VERSION
          git push origin $LATEST_WP_VERSION
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token $GH_PATH" \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/build.yml/dispatches \
            -d '{"ref":"refs/tags/'"$LATEST_WP_VERSION"'"}'
        else
          echo "Latest version is already tagged."
        fi
