name: Check WordPress Version and Tag

on:
  schedule:
    - cron: '0 0 * * *' # Runs this task daily at midnight

jobs:
  check-version-and-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-tags: true

    - name: Check WordPress Latest Version
      id: check_wp
      run: |
        LATEST_WP_VERSION=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].version')
        echo "LATEST_WP_VERSION=$LATEST_WP_VERSION" >> $GITHUB_ENV

    - name: Create Tag if New
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        CURRENT_VERSION=$(git tag --sort=-v:refname | head -n 1)
        if [ "$CURRENT_VERSION" != "$LATEST_WP_VERSION" ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag $LATEST_WP_VERSION
          git push origin $LATEST_WP_VERSION
        fi
